name: Build

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform:
          - 'feather_m0_express'
          - 'feather_esp32'
          - 'feather_esp32s2'
          - 'nrf52840'

    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Checkout code
      uses: actions/checkout@v3 
    - name: Checkout adafruit/ci-arduino
      uses: actions/checkout@v3
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: install lib for examples
      run: $GITHUB_WORKSPACE/bin/arduino-cli lib install "Adafruit GFX Library" "Adafruit SSD1306"

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}
