#pragma once

/* DEFINE FOR TARGET APOGEE OF ACE (IN METERS) */
#define ACE_TARGET_APOGEE 1463.04

/* DEFINE FOR DEVELOPMENT MODE OF ACE (ENABLES DEBUG PRINTS AND SIMULATION) */
#define IS_DEVELOPMENT_MODE 1

/* DEFINE FOR STRICT INITIALIZATION CHECKS (REQUIRES FULL INIT TO BEGIN) */
#define CHECK_STRICT_INITIALIZATION 0

/* DEFINE FOR PERFORMING PHYSICAL SERVO ACTUATION TEST AT INIT */
#define DO_SERVO_ACTUATE_INIT_CHECK 0