# This is a WIP file for automating `pio run` builds whenver a push is made to the Airbrakes branch
# Must redirect to a directory initialized as a native pio project

# Will have to see how well this works...

name: PlatformIO CI for Airbrakes

on:
  push:
    branches:
      - 'dev/airbrakes'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run
        working-directory: ~/Airbrakes/Controller/flight_platformio  # point to native PIO project root
